baseURL = "https://niceram.xyz/"
languageCode = "zh-CN"
title = "NiceBlog"
copyright = "" # ç‰ˆæƒè¯´æ˜
hasCJKLanguage = true # ç»Ÿè®¡æ±‰å­—
theme = "nicesima" # ä¸»é¢˜

paginate = 11 # æ¯é¡µçš„æ–‡ç« æ•°
enableEmoji = true # æ”¯æŒ Emoji
enableRobotsTXT = true # æ”¯æŒ robots.txt
# enableInlineShortcodes = true
# googleAnalytics = "" # Google ç»Ÿè®¡ id

# Chroma ä»£ç é«˜äº® http://gohugo.io/content-management/syntax-highlighting/
pygmentsUseClasses = true # ä½¿ç”¨è‡ªå®šä¹‰çš„ä»£ç é«˜äº®æ ·å¼
[markup]
  [markup.highlight]
    codeFences = true
    anchorLineNos = false
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "monokai"
    tabWidth = 4

[Permalinks]
 posts = "/:year/:month/:day/:filename"

[menu]
  # [[menu.main]]
  #   name = "ğŸ”§Tools"
  #   url = "/tools/"
  #   weight = 1

  [[menu.main]]
    name = "ğŸ“šBlog"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "ğŸ“‚Categories"
    url = "/categories/"
    weight = 3

  [[menu.main]]
    name = "ğŸ“ŒTags"
    url = "/tags/"
    weight = 4

  [[menu.main]]
    name = "ğŸ’¬About"
    url = "/about/"
    weight = 5

[params]
  since = "2018" # ç«™ç‚¹å»ºç«‹æ—¶é—´
  author = "niceRAM" # ä½œè€…åå­—
  avatar = "https://avatars.githubusercontent.com/u/23020764?s=460&u=e484ebce04cd653b5610b25bc34551ab693b500d&v=4"
  subtitle = "The mountain of books has a road but I'm at a loss, and the sea of learning is unlimited so that I'm inundated." # å­æ ‡é¢˜
  description = "niceRAM's Blog" # (Meta) æè¿°
  license = 'æœ¬æ–‡é‡‡ç”¨<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">çŸ¥è¯†å…±äº«ç½²å-éå•†ä¸šæ€§ä½¿ç”¨ 4.0 å›½é™…è®¸å¯åè®®</a>è¿›è¡Œè®¸å¯'

  enableGitalk = true # gitalk è¯„è®ºç³»ç»Ÿ
  enableUtteranc = false
  showPostSocialLinks = true # å¼€å¯æ¯ä¸€ç¯‡æ–‡ç« çš„ social-links æ˜¾ç¤º (ä¸ä¸»é¡µæ˜¾ç¤ºä¸å¦æ— å…³)
  easySearchedEngine = "google"
  toc = true # æ˜¯å¦å¼€å¯ç›®å½•
  autoCollapseToc = true   # è‡ªåŠ¨æ”¶èµ·ç›®å½•
  mathjax = true # æ˜¯å¦ä½¿ç”¨mathjaxï¼ˆæ•°å­¦å…¬å¼ï¼‰

  [params.gitalk] # Github: https://github.com/gitalk/gitalk
    clientId = "e2ac76297f1e7ec232f9" # Your client ID
    clientSecret = "4385d32dd8c6ab5f97856bbe2e04a1e05a237276" # Your client secret
    repo = "blog-comments" # The repo to store comments
    owner = "niceRAM" # Your GitHub ID
    admin = "niceRAM" # Required. Github repository owner and collaborators. (Users who having write access to this repository)
    id = "location.pathname" # The unique id of the page.
    labels = "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage = 15 # Pagination size, with maximum 100.
    pagerDirection = "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually = true # If it is 'false', it is auto to make a Github issue when the administrators login.
    distractionFreeMode = true # Enable hot key (cmd|ctrl + enter) submit comment.
    proxy = "https://cors-anywhere-niceblog.herokuapp.com/https://github.com/login/oauth/access_token"

  [params.utteranc] # Homepage: https://utteranc.es
    repo = "niceRAM/blog-comments" # The repo to store comments
    issueTerm = "title" # the mapping between blog posts and GitHub issues. 
    theme = "preferred-color-scheme" # Theme
    crossorigin = "anonymous" # default: anonymous

  [params.social]
    GitHub = "niceRAM"
    Twitter = "niceRAM95"
    Email = "niceniceram@gmail.com"
    Telegram = "niceRAM"
    Bilibili = "10929768/channel/detail?cid=12977"